import { apiClient } from "./client"
export const authApi = { me: () => apiClient.get("/auth/me").then(r => r.data), login: (email: string, password: string) => apiClient.post("/auth/login", { email, password }).then(r => r.data), register: (email: string, password: string, displayName: string) => apiClient.post("/auth/register", { email, password, displayName }).then(r => r.data), logout: () => apiClient.post("/auth/logout") }
export const marketApi = { indices: () => apiClient.get("/market/indices").then(r => r.data), breadth: () => apiClient.get("/market/breadth").then(r => r.data), snapshot: () => apiClient.get("/market/snapshot").then(r => r.data), heatmap: () => apiClient.get("/market/heatmap").then(r => r.data), news: (symbol?: string) => apiClient.get("/market/news", { params: { symbol } }).then(r => r.data), search: (q: string) => apiClient.get("/market/search", { params: { q } }).then(r => r.data) }
export const stockApi = { profile: (s: string) => apiClient.get(`/stock/${s}/profile`).then(r => r.data), quote: (s: string) => apiClient.get(`/stock/${s}/quote`).then(r => r.data), ohlcv: (s: string) => apiClient.get(`/stock/${s}/ohlcv`).then(r => r.data), fundamentals: (s: string) => apiClient.get(`/stock/${s}/fundamentals`).then(r => r.data), orderbook: (s: string) => apiClient.get(`/stock/${s}/orderbook`).then(r => r.data), trades: (s: string) => apiClient.get(`/stock/${s}/trades`).then(r => r.data), factors: (s: string) => apiClient.get(`/stock/${s}/factor-scores`).then(r => r.data), technical: (s: string) => apiClient.get(`/stock/${s}/technical-indicators`).then(r => r.data), news: (s: string) => apiClient.get(`/stock/${s}/news`).then(r => r.data) }
export const portfolioApi = { summary: () => apiClient.get("/portfolio/summary").then(r => r.data), positions: () => apiClient.get("/portfolio/positions").then(r => r.data), performance: () => apiClient.get("/portfolio/performance").then(r => r.data), risks: () => apiClient.get("/portfolio/risk-metrics").then(r => r.data), orders: () => apiClient.get("/portfolio/orders").then(r => r.data), order: (body: unknown) => apiClient.post("/portfolio/order", body).then(r => r.data) }
export const workspaceApi = { overview: () => apiClient.get("/workspace/overview").then(r => r.data), agent: () => apiClient.get("/workspace/agent").then(r => r.data), mlFund: () => apiClient.get("/workspace/ml-fund").then(r => r.data), research: () => apiClient.get("/workspace/research").then(r => r.data), watchlists: () => apiClient.get("/workspace/watchlists").then(r => r.data), createWatchlist: (body: { name: string; symbols: string[] }) => apiClient.post("/workspace/watchlists", body).then(r => r.data), updateWatchlist: (id: string, body: { name?: string; symbols?: string[] }) => apiClient.patch(`/workspace/watchlists/${id}`, body).then(r => r.data), deleteWatchlist: (id: string) => apiClient.delete(`/workspace/watchlists/${id}`) }
export const screenerApi = { filter: (filters: Record<string, unknown> = {}) => apiClient.post("/screener/filter", filters).then(r => r.data), presets: () => apiClient.get("/screener/presets/builtin").then(r => r.data) }
export const aiApi = { backtest: (body: Record<string, unknown>) => apiClient.post("/ai/backtest", body).then(r => r.data), backtestHistory: () => apiClient.get("/ai/backtest/history").then(r => r.data), backtestStatus: (id: string) => apiClient.get(`/ai/backtest/${id}/status`).then(r => r.data), pipelineStatus: () => apiClient.get("/ai/pipeline/status").then(r => r.data) }
export const communityApi = { posts: () => apiClient.get("/community/posts").then(r => r.data), insights: () => apiClient.get("/community/insights").then(r => r.data), experts: () => apiClient.get("/community/experts/top").then(r => r.data), createPost: (body: Record<string, unknown>) => apiClient.post("/community/posts", body).then(r => r.data), react: (id: string, type = "LIKE") => apiClient.post(`/community/posts/${id}/react`, { type }).then(r => r.data) }
